export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SENDOTP_REQUEST = 'SENDOTP_REQUEST';
export const SENDOTP_FAIL = 'SENDOTP_FAIL';
export const SENDOTP_SUCCESS = 'SENDOTP_SUCCESS';
export const VERIFYOTP_REQUEST = 'VERIFYOTP_REQUEST';
export const VERIFYOTP_FAIL = 'VERIFYOTP_FAIL';
export const VERIFYOTP_SUCCESS = 'VERIFYOTP_SUCCESS';
export const RESET_REQUEST = 'RESET_REQUEST';
export const RESET_FAIL = 'RESET_FAIL';
export const RESET_SUCCESS = 'RESET_SUCCESS';
export const UPLOAD_IMAGE_REQUEST = 'UPLOAD_IMAGE_REQUEST';
export const UPLOAD_IMAGE_FAIL = 'UPLOAD_IMAGE_FAIL';
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS';
export const GET_CITIES_REQUEST = 'GET_CITIES_REQUEST';
export const GET_CITIES_FAIL = 'GET_CITIES_FAIL';
export const GET_CITIES_SUCCESS = 'GET_CITIES_SUCCESS';
export const SEAECH_CITY_REQUEST = 'SEAECH_CITY_REQUEST';
export const SEAECH_CITY_FAIL = 'SEAECH_CITY_FAIL';
export const SEAECH_CITY_SUCCESS = 'SEAECH_CITY_SUCCESS';
export const GETAGENTS_REQUEST = 'GETAGENTS_REQUEST';
export const GETAGENTS_FAIL = 'GETAGENTS_FAIL';
export const GETAGENTS_SUCCESS = 'GETAGENTS_SUCCESS';
export const GETUSER_REQUEST = 'GETUSER_REQUEST';
export const GETUSER_FAIL = 'GETUSER_FAIL';
export const GETUSER_SUCCESS = 'GETUSER_SUCCESS';
export const UPDATEUSER_REQUEST = 'UPDATEUSER_REQUEST';
export const UPDATEUSER_FAIL = 'UPDATEUSER_FAIL';
export const UPDATEUSER_SUCCESS = 'UPDATEUSER_SUCCESS';
export const UPDATE_STATUS_REQUEST = 'UPDATE_STATUS_REQUEST';
export const UPDATE_STATUS_FAIL = 'UPDATE_STATUS_FAIL';
export const UPDATE_STATUS_SUCCESS = 'UPDATE_STATUS_SUCCESS';
export const SAVE_INTERESTS_REQUEST = 'SAVE_INTERESTS_REQUEST';
export const SAVE_INTERESTS_FAIL = 'SAVE_INTERESTS_FAIL';
export const SAVE_INTERESTS_SUCCESS = 'SAVE_INTERESTS_SUCCESS';
export const SAVE_CITY = 'SAVE_CITY';
export const SAVE_ADDRESS = 'SAVE_ADDRESS';
export const SHORTLIST_AGENTS_REQUEST = 'SHORTLIST_AGENTS_REQUEST';
export const SHORTLIST_AGENTS_FAIL = 'SHORTLIST_AGENTS_FAIL';
export const SHORTLIST_AGENTS_SUCCESS = 'SHORTLIST_AGENTS_SUCCESS';
export const GET_FEE_REQUEST = 'GET_FEE_REQUEST';
export const GET_FEE_FAIL = 'GET_FEE_FAIL';
export const GET_FEE_SUCCESS = 'GET_FEE_SUCCESS';
export const NOTIFICATION_DETAILS = 'NOTIFICATION_DETAILS';
export const SCREEN_NAME = 'SCREEN_NAME';

export const GET_SHORTLIST_AGENTS_REQUEST = 'GET_SHORTLIST_AGENTS_REQUEST';
export const GET_SHORTLIST_AGENTS_FAIL = 'GET_SHORTLIST_AGENTS_FAIL';
export const GET_SHORTLIST_AGENTS_SUCCESS = 'GET_SHORTLIST_AGENTS_SUCCESS';

export const CHANGE_CURRENT_PASS_REQUEST = 'CHANGE_CURRENT_PASS_REQUEST';
export const CHANGE_CURRENT_PASS_FAIL = 'CHANGE_CURRENT_PASS_FAIL';
export const CHANGE_CURRENT_PASS_SUCCESS = 'CHANGE_CURRENT_PASS_SUCCESS';
export const LOADER_REQUEST = 'LOADER_REQUEST';
export const LOADER_SUCCESS = 'LOADER_SUCCESS';
export const LOADER_FAIL = 'LOADER_FAIL';

export const ADD_CARD_REQUEST = 'ADD_CARD_REQUEST';
export const ADD_CARD_SUCCESS = 'ADD_CARD_SUCCESS';
export const ADD_CARD_FAIL = 'ADD_CARD_FAIL';

export const GET_CARDS_REQUEST = 'GET_CARDS_REQUEST';
export const GET_CARDS_SUCCESS = 'GET_CARDS_SUCCESS';
export const GET_CARDS_FAIL = 'GET_CARDS_FAIL';

export const DELETE_CARD_REQUEST = 'DELETE_CARDS_REQUEST';
export const DELETE_CARD_SUCCESS = 'DELETE_CARDS_SUCCESS';
export const DELETE_CARD_FAIL = 'DELETE_CARDS_FAIL';
export const GET_INTEREST_REQUEST = 'GET_INTEREST_REQUEST';
export const GET_INTEREST_FAIL = 'GET_INTEREST_FAIL';
export const GET_INTEREST_SUCCESS = 'GET_INTEREST_SUCCESS';
export const UPDATE_INTEREST_REQUEST = 'UPDATE_INTEREST_REQUEST';
export const UPDATE_INTEREST_FAIL = 'UPDATE_INTEREST_FAIL';
export const UPDATE_INTEREST_SUCCESS = 'UPDATE_INTEREST_SUCCESS';

export const GET_ACTIVE_TOURS_REQUEST = 'GET_ACTIVE_TOURS_REQUEST';
export const GET_ACTIVE_TOURS_FAIL = 'GET_ACTIVE_TOURS_FAIL';
export const GET_ACTIVE_TOURS_SUCCESS = 'GET_ACTIVE_TOURS_SUCCESS';

export const UPLOAD_VIDEO_REQUEST = 'UPLOAD_VIDEO_REQUEST';
export const UPLOAD_VIDEO_FAIL = 'UPLOAD_VIDEO_FAIL';
export const UPLOAD_VIDEO_SUCCESS = 'UPLOAD_VIDEO_SUCCESS';

export const MAKE_PAYMENT_REQUEST = 'MAKE_PAYMENT_REQUEST';
export const MAKE_PAYMENT_FAIL = 'MAKE_PAYMENT_FAIL';
export const MAKE_PAYMENT_SUCCESS = 'MAKE_PAYMENT_SUCCESS';
export const IMAGE_UPLOAD_REQUEST = 'IMAGE_UPLOAD_REQUEST';
export const IMAGE_UPLOAD_FAIL = 'IMAGE_UPLOAD_FAIL';
export const IMAGE_UPLOAD_SUCCESS = 'IMAGE_UPLOAD_SUCCESS';
export const UPDATE_TOUR_REQUEST = 'UPDATE_TOUR_REQUEST';
export const UPDATE_TOUR_FAIL = 'UPDATE_TOUR_FAIL';
export const UPDATE_TOUR_SUCCESS = 'UPDATE_TOUR_SUCCESS';
export const TRANSACTION_LIST_REQUEST = 'TRANSACTION_LIST_REQUEST';
export const TRANSACTION_LIST_FAIL = 'TRANSACTION_LIST_FAIL';
export const TRANSACTION_LIST_SUCCESS = 'TRANSACTION_LIST_SUCCESS';
export const TRANSACTION_LIST_APPEND_SUCCESS =
  'TRANSACTION_LIST_APPEND_SUCCESS';

export const GIVE_RATING_REQUEST = 'GIVE_RATING_REQUEST';
export const GIVE_RATING_FAIL = 'GIVE_RATING_FAIL';
export const GIVE_RATING_SUCCESS = 'GIVE_RATING_SUCCESS';

export const GET_CHAT_ID_REQUEST = 'GET_CHAT_ID_REQUEST';
export const GET_CHAT_ID_FAIL = 'GET_CHAT_ID_FAIL';
export const GET_CHAT_ID_SUCCESS = 'GET_CHAT_ID_SUCCESS';

export const GET_PREV_CHAT_REQUEST = 'GET_PREV_CHAT_REQUEST';
export const GET_PREV_CHAT_FAIL = 'GET_PREV_CHAT_FAIL';
export const GET_PREV_CHAT_SUCCESS = 'GET_PREV_CHAT_SUCCESS';

export const GET_CHAT_TOKEN_REQUEST = 'GET_CHAT_TOKEN_REQUEST';
export const GET_CHAT_TOKEN_FAIL = 'GET_CHAT_TOKEN_FAIL';
export const GET_CHAT_TOKEN_SUCCESS = 'GET_CHAT_TOKEN_SUCCESS';

export const GET_AVAILABLE_CITIES_REQUEST = 'GET_AVAILABLE_CITIES_REQUEST';
export const GET_AVAILABLE_CITIES_FAIL = 'GET_AVAILABLE_CITIES_FAIL';
export const GET_AVAILABLE_CITIES_SUCCESS = 'GET_AVAILABLE_CITIES_SUCCESS';

export const CREATE_ROOM_REQUEST = 'CREATE_ROOM_REQUEST';
export const CREATE_ROOM_FAIL = 'CREATE_ROOM_FAIL';
export const CREATE_ROOM_SUCCESS = 'CREATE_ROOM_SUCCESS';

export const SAVE_CHAT_TOKEN = 'SAVE_CHAT_TOKEN';
export const GET_PREV_CHAT_APPEND_SUCCESS = 'GET_PREV_CHAT_APPEND_SUCCESS';
export const APP_ACTIVE_STATUS = 'APP_ACTIVE_STATUS';

export const GET_COMPLETED_REQUEST = 'GET_COMPLETED_REQUEST';
export const GET_COMPLETED_FAIL = 'GET_COMPLETED_FAIL';
export const GET_COMPLETED_SUCCESS = 'GET_COMPLETED_SUCCESS';

export const RATING_REQUEST = 'RATING_REQUEST';
export const RATING_FAIL = 'RATING_FAIL';
export const RATING_SUCCESS = 'RATING_SUCCESS';

export const GETAGENTS_APPEND_SUCCESS = 'GETAGENTS_APPEND_SUCCESS';
